### ISSUE TITLE
Unable to load from NMRiH 1.13.1

### ISSUE THREAD

**Issue by overmase** [dysphie/nmo-guard#7]
OS : Windows
    SourceMod Version: 1.11.0.6917
    SourcePawn Engine: 1.11.0.6917, jit-x86 (build 1.11.0.6917)
    SourcePawn API: v1 = 5, v2 = 16
    Compiled on: Oct 29 2022 09:49:17
    Built from: https://github.com/alliedmodders/sourcemod/commit/58f0ca47
    Build ID: 6917:58f0ca47

[SM] Blaming: nmo-guard.smx
[SM] Call stack trace:
[SM]   [0] SetFailState
[SM]   [1] Line 162, nmo-guard\objective-manager.sp::ObjectiveManager_LoadGameData
[SM]   [2] Line 579, d:\Data\Dev\sourcemod\nmo-guard\scripting\nmo-guard.sp::LoadGamedata
[SM]   [3] Line 416, d:\Data\Dev\sourcemod\nmo-guard\scripting\nmo-guard.sp::OnPluginStart
[SM] Unable to load plugin "nmo-guard.smx": Error detected in plugin startup (see error logs)

**Comment by dysphie** [comment]
Thanks, fixed in 0.3.8
